name: Deploy Web to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:3.38.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Web
        run: flutter build web --release

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
